//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

public partial class hctDBEntities : ObjectContext
{
    public const string ConnectionString = "name=hctDBEntities";
    public const string ContainerName = "hctDBEntities";

    #region Constructors

    public hctDBEntities()
        : base(ConnectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public hctDBEntities(string connectionString)
        : base(connectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public hctDBEntities(EntityConnection connection)
        : base(connection, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    #endregion

    #region ObjectSet Properties

    public ObjectSet<Address> Addresses
    {
        get { return _addresses  ?? (_addresses = CreateObjectSet<Address>("Addresses")); }
    }
    private ObjectSet<Address> _addresses;

    public ObjectSet<AppItem> AppItems
    {
        get { return _appItems  ?? (_appItems = CreateObjectSet<AppItem>("AppItems")); }
    }
    private ObjectSet<AppItem> _appItems;

    public ObjectSet<Area> Areas
    {
        get { return _areas  ?? (_areas = CreateObjectSet<Area>("Areas")); }
    }
    private ObjectSet<Area> _areas;

    public ObjectSet<CleaningType> CleaningTypes
    {
        get { return _cleaningTypes  ?? (_cleaningTypes = CreateObjectSet<CleaningType>("CleaningTypes")); }
    }
    private ObjectSet<CleaningType> _cleaningTypes;

    public ObjectSet<Customer> Customers
    {
        get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
    }
    private ObjectSet<Customer> _customers;

    public ObjectSet<Employee> Employees
    {
        get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
    }
    private ObjectSet<Employee> _employees;

    public ObjectSet<Event> Events
    {
        get { return _events  ?? (_events = CreateObjectSet<Event>("Events")); }
    }
    private ObjectSet<Event> _events;

    public ObjectSet<HouseItem> HouseItems
    {
        get { return _houseItems  ?? (_houseItems = CreateObjectSet<HouseItem>("HouseItems")); }
    }
    private ObjectSet<HouseItem> _houseItems;

    public ObjectSet<HouseType> HouseTypes
    {
        get { return _houseTypes  ?? (_houseTypes = CreateObjectSet<HouseType>("HouseTypes")); }
    }
    private ObjectSet<HouseType> _houseTypes;

    public ObjectSet<Invoice> Invoices
    {
        get { return _invoices  ?? (_invoices = CreateObjectSet<Invoice>("Invoices")); }
    }
    private ObjectSet<Invoice> _invoices;

    public ObjectSet<OptionItem> OptionItems
    {
        get { return _optionItems  ?? (_optionItems = CreateObjectSet<OptionItem>("OptionItems")); }
    }
    private ObjectSet<OptionItem> _optionItems;

    public ObjectSet<Person> People
    {
        get { return _people  ?? (_people = CreateObjectSet<Person>("People")); }
    }
    private ObjectSet<Person> _people;

    public ObjectSet<PresetItem> PresetItems
    {
        get { return _presetItems  ?? (_presetItems = CreateObjectSet<PresetItem>("PresetItems")); }
    }
    private ObjectSet<PresetItem> _presetItems;

    public ObjectSet<Property> Properties
    {
        get { return _properties  ?? (_properties = CreateObjectSet<Property>("Properties")); }
    }
    private ObjectSet<Property> _properties;

    public ObjectSet<Quote> Quotes
    {
        get { return _quotes  ?? (_quotes = CreateObjectSet<Quote>("Quotes")); }
    }
    private ObjectSet<Quote> _quotes;

    public ObjectSet<RoomItem> RoomItems
    {
        get { return _roomItems  ?? (_roomItems = CreateObjectSet<RoomItem>("RoomItems")); }
    }
    private ObjectSet<RoomItem> _roomItems;

    public ObjectSet<Room> Rooms
    {
        get { return _rooms  ?? (_rooms = CreateObjectSet<Room>("Rooms")); }
    }
    private ObjectSet<Room> _rooms;

    public ObjectSet<RTQApp> RTQApps
    {
        get { return _rTQApps  ?? (_rTQApps = CreateObjectSet<RTQApp>("RTQApps")); }
    }
    private ObjectSet<RTQApp> _rTQApps;

    public ObjectSet<RTQOption> RTQOptions
    {
        get { return _rTQOptions  ?? (_rTQOptions = CreateObjectSet<RTQOption>("RTQOptions")); }
    }
    private ObjectSet<RTQOption> _rTQOptions;

    public ObjectSet<RTQOptionSub> RTQOptionSubs
    {
        get { return _rTQOptionSubs  ?? (_rTQOptionSubs = CreateObjectSet<RTQOptionSub>("RTQOptionSubs")); }
    }
    private ObjectSet<RTQOptionSub> _rTQOptionSubs;

    #endregion

}
