//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Address
{
    public Address()
    {
        this.Employees = new HashSet<Employee>();
        this.Properties = new HashSet<Property>();
    }

    public int Id { get; set; }
    public Nullable<int> bldg { get; set; }
    public Nullable<int> unit { get; set; }
    public string street { get; set; }
    public string city { get; set; }
    public string postal { get; set; }

    public virtual ICollection<Employee> Employees { get; set; }
    public virtual ICollection<Property> Properties { get; set; }
}

public partial class AppItem
{
    public AppItem()
    {
        this.OptionItems = new HashSet<OptionItem>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public int RoomItem_Id { get; set; }

    public virtual ICollection<OptionItem> OptionItems { get; set; }
    public virtual RoomItem RoomItem { get; set; }
}

public partial class Area
{
    public Area()
    {
        this.Properties = new HashSet<Property>();
    }

    public int Id { get; set; }
    public string fromMin { get; set; }
    public string toMax { get; set; }
    public Nullable<float> areaVal { get; set; }

    public virtual ICollection<Property> Properties { get; set; }
}

public partial class CleaningType
{
    public CleaningType()
    {
        this.HouseItems = new HashSet<HouseItem>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<float> cTypeValue { get; set; }
    public string description { get; set; }

    public virtual ICollection<HouseItem> HouseItems { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Invoices = new HashSet<Invoice>();
        this.People = new HashSet<Person>();
        this.Properties = new HashSet<Property>();
    }

    public int Id { get; set; }
    public string custID { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> joinDate { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; }
    public virtual ICollection<Person> People { get; set; }
    public virtual ICollection<Property> Properties { get; set; }
}

public partial class Employee
{
    public int Id { get; set; }
    public string empID { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> hireDate { get; set; }
    public Nullable<System.DateTime> removeDate { get; set; }
    public string type { get; set; }
    public int Address_Id { get; set; }
    public Nullable<decimal> rate { get; set; }
    public string fname { get; set; }
    public string lname { get; set; }
    public string homePhone { get; set; }
    public string workPhone { get; set; }
    public string email1 { get; set; }
    public string email2 { get; set; }
    public string mobilePhone { get; set; }

    public virtual Address Address { get; set; }
}

public partial class Event
{
    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<System.DateTime> startDate { get; set; }
    public Nullable<System.DateTime> endDate { get; set; }
    public Nullable<int> startTime { get; set; }
    public Nullable<int> endTime { get; set; }
    public int Invoice_Id { get; set; }
    public string allDay { get; set; }
    public string eventId { get; set; }
    public string empList { get; set; }

    public virtual Invoice Invoice { get; set; }
}

public partial class HouseItem
{
    public HouseItem()
    {
        this.RoomItems = new HashSet<RoomItem>();
    }

    public int Id { get; set; }
    public string otherInfo { get; set; }
    public int CleaningType_Id { get; set; }
    public string HouseType { get; set; }
    public string Area { get; set; }
    public string Pets { get; set; }
    public string HouseName { get; set; }

    public virtual CleaningType CleaningType { get; set; }
    public virtual ICollection<RoomItem> RoomItems { get; set; }
}

public partial class HouseType
{
    public HouseType()
    {
        this.Properties = new HashSet<Property>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<float> hTypeValue { get; set; }
    public string description { get; set; }

    public virtual ICollection<Property> Properties { get; set; }
}

public partial class Invoice
{
    public Invoice()
    {
        this.Events = new HashSet<Event>();
    }

    public int Id { get; set; }
    public string InvoiceID { get; set; }
    public string name { get; set; }
    public Nullable<System.DateTime> dateCreated { get; set; }
    public Nullable<System.DateTime> dateModified { get; set; }
    public string paymentStatus { get; set; }
    public string jobStatus { get; set; }
    public string paymentMethod { get; set; }
    public Nullable<System.DateTime> paymentDate { get; set; }
    public int Customer_Id { get; set; }
    public int Quote_Id { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual ICollection<Event> Events { get; set; }
    public virtual Quote Quote { get; set; }
}

public partial class OptionItem
{
    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<int> time { get; set; }
    public int AppItem_Id { get; set; }

    public virtual AppItem AppItem { get; set; }
}

public partial class Person
{
    public int Id { get; set; }
    public string fname { get; set; }
    public string lname { get; set; }
    public string homePhone { get; set; }
    public string workPhone { get; set; }
    public string mobilePhone { get; set; }
    public string email1 { get; set; }
    public string email2 { get; set; }
    public Nullable<int> Customer_Id { get; set; }

    public virtual Customer Customer { get; set; }
}

public partial class PresetItem
{
    public int Id { get; set; }
    public Nullable<decimal> price { get; set; }
    public Nullable<int> time { get; set; }
    public string description { get; set; }
    public string title { get; set; }
    public Nullable<System.DateTime> startDate { get; set; }
    public Nullable<System.DateTime> endDate { get; set; }
}

public partial class Property
{
    public int Id { get; set; }
    public string name { get; set; }
    public int Address_Id { get; set; }
    public int Area_Id { get; set; }
    public int Customer_Id { get; set; }
    public int HouseType_Id { get; set; }

    public virtual Address Address { get; set; }
    public virtual Area Area { get; set; }
    public virtual Customer Customer { get; set; }
    public virtual HouseType HouseType { get; set; }
}

public partial class Quote
{
    public Quote()
    {
        this.Invoices = new HashSet<Invoice>();
    }

    public int Id { get; set; }
    public string quoteCode { get; set; }
    public Nullable<decimal> totalPrice { get; set; }
    public Nullable<int> totalTime { get; set; }
    public string name { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> DateCreated { get; set; }
    public string quotePath { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; }
}

public partial class Room
{
    public Room()
    {
        this.RTQApps = new HashSet<RTQApp>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public string description { get; set; }

    public virtual ICollection<RTQApp> RTQApps { get; set; }
}

public partial class RoomItem
{
    public RoomItem()
    {
        this.AppItems = new HashSet<AppItem>();
    }

    public int Id { get; set; }
    public string nickName { get; set; }
    public string name { get; set; }
    public int HouseItem_Id { get; set; }

    public virtual ICollection<AppItem> AppItems { get; set; }
    public virtual HouseItem HouseItem { get; set; }
}

public partial class RTQApp
{
    public RTQApp()
    {
        this.RTQOptions = new HashSet<RTQOption>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public string status { get; set; }
    public string description { get; set; }
    public int Room_Id { get; set; }

    public virtual Room Room { get; set; }
    public virtual ICollection<RTQOption> RTQOptions { get; set; }
}

public partial class RTQOption
{
    public RTQOption()
    {
        this.RTQOptionSubs = new HashSet<RTQOptionSub>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<int> time { get; set; }
    public string description { get; set; }
    public string status { get; set; }
    public int RTQApp_Id { get; set; }
    public string ctype { get; set; }

    public virtual RTQApp RTQApp { get; set; }
    public virtual ICollection<RTQOptionSub> RTQOptionSubs { get; set; }
}

public partial class RTQOptionSub
{
    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<int> time { get; set; }
    public string description { get; set; }
    public int RTQOption_Id { get; set; }
    public string ctype { get; set; }

    public virtual RTQOption RTQOption { get; set; }
}
